collections:
    darknet:
        output: true
    courses:
        output: true
    projects:
        output: true
    publications:
        output: true
defaults:
    -
        scope:
            path: ""
            type: "darknet"
        values:
            layout: "darknet"
            order: 100
    -
        scope:
            path: ""
            type: "projects"
        values:
            layout: "projects"
            order: 100
    -
        scope:
            path: ""
            type: "publications"
        values:
            layout: "publications"
